# Generated by Django 5.2.13 on 2026-08-17 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_historicalproject'),
        ('suites', '0003_historicalsuite_historicaltestplan'),
        ('tests', '0005_historicalcase_historicalfunccase_historicalstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('title', models.CharField(max_length=500, verbose_name='缺陷标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='缺陷描述')),
                ('severity', models.IntegerField(choices=[(1, '致命'), (2, '严重'), (3, '一般'), (4, '轻微')], default=3, verbose_name='严重程度')),
                ('priority', models.IntegerField(choices=[(1, '紧急'), (2, '高'), (3, '中'), (4, '低')], default=3, verbose_name='优先级')),
                ('defect_type', models.IntegerField(choices=[(1, '代码问题-前端'), (2, '代码问题-后端'), (3, '设计如此'), (4, '重复BUG'), (5, '需求变动'), (6, 'UI样式'), (7, '设计缺陷')], default=1, verbose_name='BUG类型')),
                ('status', models.IntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已解决'), (4, '已关闭')], default=1, verbose_name='状态')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_assignee', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.case')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suites.testplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '缺陷表',
                'verbose_name_plural': '缺陷表',
                'db_table': 'tb_defect',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DefectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defects.defect', verbose_name='所属缺陷')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '缺陷评论',
                'verbose_name_plural': '缺陷评论',
                'db_table': 'tb_defect_comment',
                'ordering': ['-create_time'],
            },
        ),
    ]
