# Generated by Django 5.2.17 on 2026-08-17 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_defect_rich_text_fields'),
        ('envs', '0002_historicalenv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='due_date',
        ),
        migrations.AddField(
            model_name='defect',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='envs.module', verbose_name='所属模块'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defect_assignee', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
    ]
