# Generated by Django 5.2.13 on 2026-08-19 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0005_defect_func_cases_manytomany'),
        ('tests', '0005_historicalcase_historicalfunccase_historicalstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defect_owner', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='func_cases',
            field=models.ManyToManyField(blank=True, help_text='关联功能用例', to='tests.funccase'),
        ),
    ]
