# Generated by Django 4.2.30 on 2026-06-07 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='项目名称', max_length=50)),
                ('desc', models.CharField(help_text='项目描述', max_length=200, verbose_name='项目描述')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'db_table': 'tb_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('role', models.ForeignKey(help_text='项目内角色', on_delete=django.db.models.deletion.DO_NOTHING, to='users.role')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目成员表',
                'verbose_name_plural': '项目成员表',
                'db_table': 'tb_project_member',
            },
        ),
        migrations.CreateModel(
            name='ProjectAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('status', models.BooleanField(default=False, verbose_name='审核状态')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目成员申请表',
                'db_table': 'tb_project_appeal',
            },
        ),
        migrations.CreateModel(
            name='AiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('provider_name', models.CharField(help_text='前端显示的供应商名称', max_length=100, verbose_name='供应商名称')),
                ('api_key', models.CharField(help_text='调用 API 所需的密钥', max_length=512, verbose_name='API Key')),
                ('api_url', models.URLField(help_text='API 的请求地址', max_length=500, verbose_name='API URL')),
                ('model_name', models.CharField(db_index=True, help_text='使用的具体模型，如 deepseek-chat', max_length=100, verbose_name='模型名称')),
                ('is_active', models.BooleanField(default=True, help_text='勾选表示该配置可用，否则不可用', verbose_name='是否启用')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='配置所属的项目', on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to='projects.project', verbose_name='所属项目')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI大模型接入配置',
                'verbose_name_plural': 'AI大模型接入配置',
                'db_table': 'tb_project_ai_config',
            },
        ),
        migrations.CreateModel(
            name='ProjectMsgPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('push_type', models.IntegerField(choices=[(1, '飞书'), (2, '钉钉'), (3, '邮箱')], help_text='推送渠道类型', verbose_name='推送类型')),
                ('webhook_url', models.CharField(blank=True, default='', help_text='飞书或钉钉的Webhook地址', max_length=500, verbose_name='Webhook地址')),
                ('email_host', models.CharField(blank=True, default='', help_text='SMTP服务器地址', max_length=100, verbose_name='邮箱SMTP主机')),
                ('email_port', models.IntegerField(default=25, help_text='SMTP服务器端口', verbose_name='邮箱SMTP端口')),
                ('email_user', models.CharField(blank=True, default='', help_text='发送邮件的邮箱账号', max_length=100, verbose_name='邮箱账号')),
                ('email_password', models.CharField(blank=True, default='', help_text='邮箱密码或授权码（钉钉/飞书用作签名密钥，邮箱用作SMTP认证）', max_length=200, verbose_name='邮箱密码或授权码')),
                ('email_to', models.CharField(blank=True, default='', help_text='接收消息的邮箱地址，多个邮箱用逗号分隔', max_length=500, verbose_name='收件人邮箱')),
                ('is_active', models.BooleanField(default=True, help_text='勾选表示该配置可用，否则不可用', verbose_name='是否启用')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='配置所属的项目', on_delete=django.db.models.deletion.CASCADE, related_name='msg_push_configs', to='projects.project', verbose_name='所属项目')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目消息推送配置',
                'verbose_name_plural': '项目消息推送配置',
                'db_table': 'tb_project_msg_push',
                'unique_together': {('project', 'push_type')},
            },
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('project', 'user'), name='unique_active_project_member'),
        ),
        migrations.AlterUniqueTogether(
            name='projectappeal',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='aiconfig',
            index=models.Index(fields=['project', 'is_active'], name='tb_project__project_4f59c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiconfig',
            unique_together={('project', 'provider_name', 'model_name')},
        ),
    ]
