# Generated by Django 5.2.17 on 2026-09-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0002_historicalenv'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='页面地址'),
        ),
    ]
