# Generated by Django 5.2 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0003_module_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envdb',
            name='type',
            field=models.IntegerField(
                choices=[(1, 'MySQL'), (2, 'PostgreSQL'), (3, 'REDIS'), (4, 'Oracle'), (5, '达梦8')],
                default=1,
                verbose_name='数据库类型',
            ),
        ),
    ]
