# Generated by Django 5.2.17 on 2026-08-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_historicalpythonscript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-create_time'], 'verbose_name': '文件上传', 'verbose_name_plural': '文件上传'},
        ),
    ]
