# Generated by Django 5.2.17 on 2026-08-14 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0002_historicalproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('username', models.CharField(default='', max_length=150, verbose_name='操作人用户名')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('login', '登录'), ('logout', '登出')], max_length=20, verbose_name='操作类型')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP方法')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端IP')),
                ('module', models.CharField(default='', max_length=50, verbose_name='操作模块')),
                ('request_body', models.TextField(blank=True, default='', verbose_name='请求体')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='响应体')),
                ('before_data', models.TextField(blank=True, default='', verbose_name='操作前数据')),
                ('after_data', models.TextField(blank=True, default='', verbose_name='操作后数据')),
                ('status_code', models.IntegerField(default=200, verbose_name='响应状态码')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='操作描述')),
                ('object_id', models.CharField(blank=True, default='', max_length=50, verbose_name='对象ID')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='模型类型')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='关联项目')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'tb_audit_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
