# Generated by Django 4.2.30 on 2026-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fail_reason',
            field=models.TextField(blank=True, default='', verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='message',
            name='failed_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='失败数'),
        ),
        migrations.AddField(
            model_name='message',
            name='success_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='成功数'),
        ),
        migrations.AddField(
            model_name='message',
            name='total_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='总数'),
        ),
    ]
