# Generated by Django 4.2.30 on 2026-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0002_message_fail_reason_message_failed_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='task_status',
            field=models.IntegerField(blank=True, choices=[(1, '进行中'), (2, '已完成'), (3, '失败')], null=True, verbose_name='任务状态'),
        ),
    ]
