# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_historicalelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='status',
            field=models.IntegerField(choices=[(0, '待修改'), (1, '已发布'), (2, '待废弃')], default=1, verbose_name='元素状态'),
        ),
        migrations.AddField(
            model_name='historicalelement',
            name='status',
            field=models.IntegerField(choices=[(0, '待修改'), (1, '已发布'), (2, '待废弃')], default=1, verbose_name='元素状态'),
        ),
    ]