# Generated by Django 4.2.30 on 2026-06-07 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(1, '已发布'), (2, '设计中'), (3, '待确定'), (4, '开发'), (5, '对接'), (6, '测试'), (7, '完成'), (8, '异常'), (9, '维护'), (10, '废弃')], default=1, verbose_name='接口状态')),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('url', models.CharField(max_length=200, verbose_name='请求地址')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('headers', models.JSONField(verbose_name='请求头')),
                ('body_type', models.IntegerField(choices=[(1, 'JSON'), (2, 'Form-data')], default=1, verbose_name='body类型')),
                ('json', models.JSONField(verbose_name='json/application')),
                ('api_json_type', models.CharField(default='object', max_length=15, verbose_name='json根类型')),
                ('api_response_type', models.CharField(default='object', max_length=15, verbose_name='response根类型')),
                ('data', models.JSONField(verbose_name='form-data')),
                ('params', models.JSONField(verbose_name='查询参数')),
                ('response', models.JSONField(verbose_name='数据返回体')),
                ('response_tree', models.JSONField(default=list, verbose_name='数据返回体')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envs.servicemodule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envs.service', verbose_name='所属服务')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '接口表',
                'verbose_name_plural': '接口表',
                'db_table': 'tb_api',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='mock名称')),
                ('desc', models.CharField(max_length=200, verbose_name='mock描述')),
                ('is_enable', models.BooleanField(default=False, help_text='是否启用', verbose_name='是否启用')),
                ('headers', models.JSONField(verbose_name='请求头')),
                ('json', models.JSONField(default=list, verbose_name='json/application')),
                ('status_code', models.IntegerField(default=200, verbose_name='mock响应状态码')),
                ('timeout', models.IntegerField(default=0, verbose_name='mock延长响应时间')),
                ('json_tree', models.JSONField(default=list, verbose_name='json_tree')),
                ('body_type', models.IntegerField(choices=[(1, 'JSON'), (2, 'Form-data')], default=1, verbose_name='body类型')),
                ('response_type', models.IntegerField(choices=[(1, 'JSON'), (2, '跟随API文档')], default=2, verbose_name='resbody类型')),
                ('api_json_type', models.CharField(default='object', max_length=15, verbose_name='json根类型')),
                ('api_response_type', models.CharField(default='object', max_length=15, verbose_name='response根类型')),
                ('data', models.JSONField(verbose_name='form-data')),
                ('params', models.JSONField(verbose_name='查询参数')),
                ('response', models.JSONField(default=list, verbose_name='数据返回体')),
                ('response_headers', models.JSONField(default=list, verbose_name='请求头')),
                ('response_tree', models.JSONField(default=list, verbose_name='数据返回体')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interfaces.api', verbose_name='所属接口')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '接口Mock表',
                'verbose_name_plural': '接口Mock表',
                'db_table': 'tb_api_mock',
                'ordering': ['-update_time'],
            },
        ),
    ]
