# Generated by Django 5.2.17 on 2026-08-14 12:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0002_historicalenv'),
        ('interfaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalApi',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(blank=True, editable=False, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='更新时间', verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(1, '已发布'), (2, '设计中'), (3, '待确定'), (4, '开发'), (5, '对接'), (6, '测试'), (7, '完成'), (8, '异常'), (9, '维护'), (10, '废弃')], default=1, verbose_name='接口状态')),
                ('name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('url', models.CharField(max_length=200, verbose_name='请求地址')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('headers', models.JSONField(verbose_name='请求头')),
                ('body_type', models.IntegerField(choices=[(1, 'JSON'), (2, 'Form-data')], default=1, verbose_name='body类型')),
                ('json', models.JSONField(verbose_name='json/application')),
                ('api_json_type', models.CharField(default='object', max_length=15, verbose_name='json根类型')),
                ('api_response_type', models.CharField(default='object', max_length=15, verbose_name='response根类型')),
                ('data', models.JSONField(verbose_name='form-data')),
                ('params', models.JSONField(verbose_name='查询参数')),
                ('response', models.JSONField(verbose_name='数据返回体')),
                ('response_tree', models.JSONField(default=list, verbose_name='数据返回体')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('create_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='envs.servicemodule')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='envs.service', verbose_name='所属服务')),
                ('update_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 接口表',
                'verbose_name_plural': 'historical 接口表',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
