# Generated by Django 4.2.30 on 2026-07-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='fail_is_continue',
        ),
        migrations.RemoveField(
            model_name='step',
            name='is_run',
        ),
        migrations.AddField(
            model_name='casesteps',
            name='fail_is_continue',
            field=models.IntegerField(choices=[(0, '停止测试'), (1, '继续执行'), (2, '继续执行并忽略失败')], default=0, verbose_name='步骤执行失败是否继续下一步并忽略失败'),
        ),
        migrations.AddField(
            model_name='casesteps',
            name='is_run',
            field=models.BooleanField(default=True, help_text='是否执行该步骤', verbose_name='是否执行该步骤'),
        ),
    ]
