# Generated by Django 4.2.30 on 2026-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_funccase_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funccase',
            name='case_status',
            field=models.IntegerField(choices=[(1, '待修改'), (2, '待评审'), (3, '已评审')], default=2, verbose_name='用例状态'),
        ),
    ]
