# Generated by Django 5.2.17 on 2026-09-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_historicalcase_historicalfunccase_historicalstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='web_engine_type',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='web_engine_type',
        ),
        migrations.AlterField(
            model_name='case',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='标签', to='tests.tag'),
        ),
    ]
