# Generated by Django 4.2.30 on 2026-06-07 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envs', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='报告名称')),
                ('all_case_number', models.IntegerField(default=0, verbose_name='总用例数')),
                ('success_case_number', models.IntegerField(default=0, verbose_name='成功用例数')),
                ('error_case_number', models.IntegerField(default=0, verbose_name='错误用例数')),
                ('fail_case_number', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('detail', models.JSONField(default=dict)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envs.env')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suites.testplan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suites.suite')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '报告表',
                'verbose_name_plural': '报告表',
                'db_table': 'tb_report',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='LocustReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('test_process', models.IntegerField(choices=[(1, '已完成'), (2, '压测中')], default=2, help_text='压测并发用户数')),
                ('max_user', models.IntegerField(help_text='压测并发用户数')),
                ('rate', models.IntegerField(help_text='每秒启动用户数')),
                ('cpu', models.FloatField(help_text='cpu使用率')),
                ('memory', models.FloatField(help_text='内存使用M')),
                ('duration', models.CharField(max_length=50, verbose_name='持续时间')),
                ('requests_statistics', models.JSONField(default=list)),
                ('failures_statistics', models.JSONField(default=list)),
                ('start_time', models.DateTimeField(help_text='开始时间', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(help_text='结束时间', verbose_name='结束时间')),
                ('exceptions_statistics', models.JSONField(default=list)),
                ('response_time_statistics', models.JSONField(default=list)),
                ('history', models.JSONField(default=list)),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envs.env')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '性能测试报告',
                'verbose_name_plural': '性能测试报告',
                'db_table': 'tb_locust_report',
                'ordering': ['-create_time'],
            },
        ),
    ]
