# Generated by Django 4.2.30 on 2026-06-07 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locustreport',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tests.case'),
            preserve_default=False,
        ),
    ]
