# Generated by Django 5.2.17 on 2026-08-16 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_historicalapi'),
        ('reports', '0002_locustreport_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='interfaces.api'),
        ),
    ]
