# Generated by Django 5.2.17 on 2026-09-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locustreport',
            name='test_process',
            field=models.IntegerField(choices=[(1, '已完成'), (2, '压测中'), (3, '失败')], default=2, help_text='压测并发用户数'),
        ),
    ]
