# Generated by Django 5.2.17 on 2026-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_locustreport_test_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='locustreport',
            name='fail_reason',
            field=models.TextField(blank=True, default='', verbose_name='失败原因'),
        ),
    ]
