# Generated by Django 4.2.30 on 2026-06-07 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envs', '0001_initial'),
        ('django_q', '0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='测试计划的名称', max_length=100, verbose_name='计划名称')),
                ('start_end_time', models.JSONField(help_text='计划起止时间', verbose_name='计划起止时间')),
                ('conclusion', models.TextField(blank=True, default='', help_text='测试计划的总结结论', verbose_name='测试结论')),
                ('desc', models.TextField(blank=True, default='', help_text='测试计划的详细描述', verbose_name='计划描述')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='测试计划所属的项目', on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='projects.project', verbose_name='所属项目')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'db_table': 'tb_test_plan',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='TestPlanFuncCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('exec_status', models.IntegerField(choices=[(1, '未执行'), (2, '暂缓'), (3, '已通过'), (4, '未通过'), (5, '进行中')], default=1, help_text='用例在该测试计划中的执行状态', verbose_name='执行状态')),
                ('executed_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_test_plan_cases', to=settings.AUTH_USER_MODEL, verbose_name='添加用例的人')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_test_plan_cases', to=settings.AUTH_USER_MODEL, verbose_name='执行用例的人')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plan_func_cases', to='suites.testplan', verbose_name='所属测试计划')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '测试计划功能用例',
                'verbose_name_plural': '测试计划功能用例',
                'db_table': 'tb_test_plan_func_case',
            },
        ),
        migrations.CreateModel(
            name='TestPlanFuncCaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('content', models.TextField(help_text='评论或备注内容', verbose_name='评论内容')),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plan_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('test_plan_func_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='suites.testplanfunccase', verbose_name='所属测试计划用例')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '测试计划用例评论',
                'verbose_name_plural': '测试计划用例评论',
                'db_table': 'tb_test_plan_func_case_comment',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('plant_type', models.IntegerField(choices=[(1, '功能用例'), (2, '脚本用例')], default=2, verbose_name='计划类型')),
                ('plant_model', models.IntegerField(choices=[(1, '静态模式'), (2, '动态模式')], default=2, verbose_name='计划模式')),
                ('auto_type', models.IntegerField(choices=[(1, 'API'), (2, 'WEB_UI'), (3, 'APP_UI')], default=1, verbose_name='脚本用例类型')),
                ('name', models.CharField(max_length=50, verbose_name='计划名称')),
                ('desc', models.CharField(max_length=200, verbose_name='计划描述')),
                ('rerun_times', models.IntegerField(default=0, verbose_name='脚本用例失败重试次数')),
                ('push_msg', models.BooleanField(default=True, help_text='用例执行完是否推送消息', verbose_name='用例执行完是否推送消息')),
                ('dynamic_conditions', models.JSONField(verbose_name='动态模式筛选用例条件')),
                ('start_end_time', models.JSONField(help_text='计划起止时间', verbose_name='计划起止时间')),
                ('app_executor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='envs.envappexecutor', verbose_name='所属app执行器节点')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
                ('web_executor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='envs.envwebexecutor', verbose_name='所属web执行器节点')),
            ],
            options={
                'verbose_name': '计划表',
                'verbose_name_plural': '计划表',
                'db_table': 'tb_suite',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CrontabTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='定时任务描述')),
                ('crontab', models.CharField(max_length=256, verbose_name='定时策略')),
                ('enabled', models.BooleanField(default=True, help_text='是否启用', verbose_name='启用')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_create_by', to=settings.AUTH_USER_MODEL)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envs.env', verbose_name='环境名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='所属项目')),
                ('schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.schedule')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suites.suite', verbose_name='套件名称')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_update_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'db_table': 'tb_crontab_task',
                'ordering': ['-create_time'],
            },
        ),
    ]
