# Generated by Django 4.2.30 on 2026-06-07 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        ('suites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='auto_cases',
            field=models.ManyToManyField(help_text='关联自动化用例', to='tests.case'),
        ),
        migrations.AddField(
            model_name='suite',
            name='func_cases',
            field=models.ManyToManyField(help_text='关联功能用例', to='tests.funccase'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='func_cases',
            field=models.ManyToManyField(help_text='关联的功能用例', related_name='test_plans', through='suites.TestPlanFuncCase', to='tests.funccase'),
        ),
        migrations.AddField(
            model_name='testplanfunccase',
            name='func_case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_plan_func_cases', to='tests.funccase', verbose_name='功能用例'),
            preserve_default=False,
        ),
    ]
