# Generated by Django 5.2.17 on 2026-08-14 12:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0002_historicalenv'),
        ('projects', '0002_historicalproject'),
        ('suites', '0002_suite_auto_cases_suite_func_cases_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSuite',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(blank=True, editable=False, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='更新时间', verbose_name='更新时间')),
                ('plant_type', models.IntegerField(choices=[(1, '功能用例'), (2, '脚本用例')], default=2, verbose_name='计划类型')),
                ('plant_model', models.IntegerField(choices=[(1, '静态模式'), (2, '动态模式')], default=2, verbose_name='计划模式')),
                ('auto_type', models.IntegerField(choices=[(1, 'API'), (2, 'WEB_UI'), (3, 'APP_UI')], default=1, verbose_name='脚本用例类型')),
                ('name', models.CharField(max_length=50, verbose_name='计划名称')),
                ('desc', models.CharField(max_length=200, verbose_name='计划描述')),
                ('rerun_times', models.IntegerField(default=0, verbose_name='脚本用例失败重试次数')),
                ('push_msg', models.BooleanField(default=True, help_text='用例执行完是否推送消息', verbose_name='用例执行完是否推送消息')),
                ('dynamic_conditions', models.JSONField(verbose_name='动态模式筛选用例条件')),
                ('start_end_time', models.JSONField(help_text='计划起止时间', verbose_name='计划起止时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('app_executor', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='envs.envappexecutor', verbose_name='所属app执行器节点')),
                ('create_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
                ('update_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('web_executor', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='envs.envwebexecutor', verbose_name='所属web执行器节点')),
            ],
            options={
                'verbose_name': 'historical 计划表',
                'verbose_name_plural': 'historical 计划表',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTestPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(blank=True, editable=False, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, editable=False, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(help_text='测试计划的名称', max_length=100, verbose_name='计划名称')),
                ('start_end_time', models.JSONField(help_text='计划起止时间', verbose_name='计划起止时间')),
                ('conclusion', models.TextField(blank=True, default='', help_text='测试计划的总结结论', verbose_name='测试结论')),
                ('desc', models.TextField(blank=True, default='', help_text='测试计划的详细描述', verbose_name='计划描述')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('create_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, help_text='测试计划所属的项目', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='所属项目')),
                ('update_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 测试计划',
                'verbose_name_plural': 'historical 测试计划',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
